services:
  db:
    image: mysql:8.4
    container_name: fifa-player-manager-db
    ports:
      - "${HOST_DB_PORT}:3306"
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  web:
    image: fifa-player-manager-web:dev
    build:
      context: ./apps/web
      dockerfile: web.dockerfile
    container_name: fifa-player-manager-web
    ports:
      - "${HOST_WEB_PORT}:4200"
    env_file: .env
    volumes:
      - ./apps/web:/app
      - /app/node_modules
  api:
    image: fifa-player-manager-api:dev
    build:
      context: .
      dockerfile: ./apps/api/api.dockerfile
    container_name: fifa-player-manager-api
    ports:
      - "${HOST_API_PORT}:3000"
    env_file: .env
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}?connection_limit=5
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./apps/api:/app/apps/api 
      - /app/apps/api/node_modules